### ISSUE TITLE
关于 pcrbot.com 网址的发展

### ISSUE THREAD

**Issue by yuudi** [pcrbot/www.pcrbot.com#9]
[pcrbot.com](https://www.pcrbot.com/) 建立的目的是为了整理 pcrbot 相关项目，方便大家更好发现喜欢的项目，也方便开发者向大家展示自己的项目，但现在没有达到预期的目的，可能的原因大概有：

1. 网站国内访问速度较慢。
2. 网站内容杂乱，很难找到插件。
3. 讨论度不够，发布文章无法得到反馈。
4. 发布文章不够简便，尽管右上方给出了一键发布的按钮，但仍然需要重新写 README，后续每次更新都要改文章。

解决方法：
1. 加钱。
2. 增加搜索功能。
3. 网页内嵌入评论区，或者将网站改造为 BBS。但是这需要相当多的后期维护与管理成本。
4. 发布者无需重新编写介绍，只需填写链接即可自动导入仓库的 README 文件。

欢迎补充

**Comment by noahzark** [comment]
n. 能不能快进到nonebot plugin manager/hoshino module installer/pcrbot package installer

e.g.
npm / him / pip install xxx

p.s. 手动狗头.jpg
p.s.2 你去pr就有了.gif
